#!/usr/bin/bash
# ~/.config/bspwm/panel/panel

#General stuff

PANEL_FIFO=/tmp/panel-fifo
. ~/.config/bspwm/themes/theme

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

#Content

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -s -t 100 -f 'T%s' > "$PANEL_FIFO" &

~/.config/bspwm/panel/info.sh > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | ~/.config/bspwm/panel/panel_bar | lemonbar -g 1920x${PANEL_HEIGHT} -a 30 -f "DejaVu Sans Mono-13" -f "FontAwesome-15" -f "FontAwesome-15" -B ${COLOR_BACKGROUND} -F ${COLOR_FOREGROUND} -u 4 | sh &

wait
