#!/usr/bin/bash

#General stuff

PANEL_FIFO=/tmp/panel-fifo

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"


updates() {
	echo $(checkupdates | wc -l)
}

music() {
	echo $(mpc current)
}

clock() {
	DATE=$(date "+%l:%M %p ")
	echo -n "$DATE"
}

while true; do
	buf=""
	buf="echo '${buf}Packages: $(updates)'"
	
	${buf} > $PANEL_FIFO
	sleep 1
done

cat "$PANEL_FIFO" | lemonbar -g 1920x25 -f "Source Code Pro" -B "#454545" &

wait
