#! /bin/sh

################
# BSPWM Config #
################

bspwmdir="${XDG_CONFIG_HOME:-$HOME/.config}"/bspwm
# source "$bspwmdir"/themes/theme

# $bspwmdir/panel/panel 2> /dev/null &
# $bspwmdir/bspwm/bin/mpdnotify.sh &

bspc config border_width       3
bspc config window_gap         18
bspc config top_padding        30

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config leaf_monocle	false

# for monitor in $(bspc query -M); do
# 	bspc monitor "$monitor" -d 000 001 010 011 100 101 110 111
# done

bspc monitor "DVI-I-1" -d 000 001 010 011 100 101 110 111
bspc monitor "DVI-D-0" -d 0 1 2 3 4 5 6 7

# bspc config -m DVI-D-0 top_padding 0

##############
# Bar Config #
##############

/home/adam/.config/admiral.d/admiral.sh &
/home/adam/.config/admiral.d/secondary_admiral.sh &

#############
# Wallpaper #
#############

# eval $(echo "$bspwmdir/bin/wallshuffle.sh $WALLPAPER") &

# $bspwmdir/bin/wallshuffle.sh $WALLPAPER
