#! /bin/sh
~/.config/bspwm/panel/panel 2> /dev/null &

bspc config border_width       3
bspc config window_gap         18
bspc config top_padding        30

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config leaf_monocle	false

bspc monitor -d 000 001 010 011 100 101 110 111

bspc rule -a Hexchat desktop=^2

feh --bg-fill ~/.config/bspwm/themes/wallpaper
