#!/bin/bash
# ~/.config/bspwm/panel/example_bar

. ~/.config/bspwm/panel/panel_colors

num_mon=$(bspc query -M | wc -l)

# clickable area aliases
AC='%{A:'           # start left click area
ACU='%{A4:'			# start scroll up area
ACD='%{A5:'			# start scroll down area
AB=':}'             # end click area cmd
AE='%{A}'           # end click area

# Shell commands for clickable areas
goto='bspc desktop -f'       # go to this desktop
cycle='bspc desktop -l next' # cycle tiled/monocle
winfocus='bspc window -f '   # focus on a window

while read -r line ; do
	case $line in
		T*)
			# xtitle output
			title="%{A3:~/.config/bspwm/bin/dzen_windowswitcher:}${line#?}%{A} %{B-}%{F-}"
			;;
		S*)
			# system output
			sys_infos="${line#?}%{B-}%{F-}"
			;;
		M*)
			# MPD output
			mpdout="${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					O*)
						# focused occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B${COLOR_BACKGROUND}} ${DO}%{B-}%{F-}"
						;;
					F*)
						# focused free desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B${COLOR_BACKGROUND}} ${DF}%{B-}%{F-}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_LIGHTRED}%{B${COLOR_BACKGROUND}} ${DO}%{B-}%{F-}"
						;;
					o*)
						# occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B${COLOR_BACKGROUND}} ${AC}${goto} ${name}${AB}${DO}%{B-}%{F-}${AE}"
						;;
					f*)
						# free desktop
						wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B${COLOR_BACKGROUND}} ${AC}${goto} ${name}${AB}${DF}%{B-}%{F-}${AE}"
						;;
					u*)
						# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_DARKRED}%{B${COLOR_BACKGROUND}} ${AC}${goto} ${name}${AB}${DO}%{B-}%{F-}${AE}"
						;;
					L*)
						# layout
						#wm_infos="${wm_infos}%{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{U${COLOR_BACKGROUND}}%{+o}%{+u}%{l}${AC}~/.config/bspwm/bin/menu${AB}$(echo -e " Start %{F-}")${AE}${ACD}bspc desktop -f next${AB}${ACU}bspc desktop -f prev${AB}|${wm_infos}${AE}${AE}%{c}${title}%{r}${mpdout}${sys_infos}"
done
