#!/bin/bash
#usage: ./panel | lemonbar -g 1920x25 -f "Source Code Pro" -B #454545 | sh

updates() {
	echo $(checkupdates | wc -l)
}

music() {
	echo $(mpc current)
}

clock() {
	DATE=$(date "+%l:%M %p ")
	echo -n "$DATE"
}

while true; do
	#left
	buf="%{l}"
	buf="${buf}The quick brown fox jumps over the lazy dog" #All the fun of Lorem Ipsum with none of the Latin
	
	#center
	buf="${buf}%{c}%{A4:bspc desktop -f prev:}%{A5:bspc desktop -f next:}Current workspace: $(bspc query -D -d)/111%{A}%{A}"

	#right
    buf="${buf}%{r}%{A:urxvt -x 'sudo pacman -Syu':}Updates: $(updates)%{A} "
    buf="${buf}%{A:mpc toggle:}MPD: $(music)%{A}"
    buf="${buf}$(clock)"
    
    echo "$buf"
    sleep .001;
done
